### ISSUE TITLE
Win condition

### ISSUE THREAD

**Issue by tylerdance** [tylerdance/Asteroids-game#2]
Trying to use `cancelAnimationFrame` for my win condition but having trouble getting it dialed in.

**Comment by pmacaluso3** [comment]
Right now you're calling `requestAnimationFrame` unconditionally in your `animate` function. Instead of trying to cancel the request, only make the request under certain conditions, ie, create a global `hasWon` variable or something, and only make the request if it's `false`

**Comment by tylerdance** [comment]
Ok am I still in line?

**Comment by pmacaluso3** [comment]
Sry, I will come back around to ya next
