### ISSUE TITLE
Game reset buttons

### ISSUE THREAD

**Issue by tylerdance** [tylerdance/Asteroids-game#4]
Start game button is good, but I am having trouble getting game reset button to look identical to the landing page start button.

**Comment by pmacaluso3** [comment]
There are some differences between your start button and your restart buttons:

1) The start button contains a `<span>` element, which a few `.btn-3 span` css declarations rely on.

2) Your `#restart-fail` and `#restart-win` declarations overwrite the `background` and `padding` properties from the `.btn-3` styling

Make these changes 1 at a time to see the effects
